fix: PRCR2-931 sensitive data being logged into log files
softwaregroup-bg/ut-log pull request #22
Opened 2017-11-27 12:24 UTC by vencislavdimitrov

Sensitive data was still found in error messages logged from joi, therefor we now iterate and mask the internals in the ValidationError object. Furthermore the configuration for keys to be masked is passed to the construction of the lib object instead of on every transformData method call. This way the regex for masking the data is constructed only once on application startup instead of on every log.

2017-11-28 00:55 UTC, kalinkrustev commented
We should not bind our logic to joi internals. Joi can take care of sensitive data - please read here: https://github.com/hapijs/joi/blob/v10.6.0/API.md#anystrip

If err._object is specific to joi, please make masking generic for all error properties.

2017-11-28 00:55 UTC, kalinkrustev requested changes
We should not bind our logic to joi internals. Joi can take care of sensitive data - please read here: https://github.com/hapijs/joi/blob/v10.6.0/API.md#anystrip

If err._object is specific to joi, please make masking generic for all error properties.

Also can you think of adding some property to the logged object, that indicates if masking was done. This will make it possible for better analysis where we have sensitive data and try to avoid logging it in first place.

2017-11-28 11:24 UTC, vencislavdimitrov commented
I've masked all data in the error object to make it joi agnostic. Also added new property to all masked messages containing the keys that have been masked.

2017-11-29 00:56 UTC, kalinkrustev approved these changes

2017-11-29 07:16 UTC, zetxx approved these changes

2017-11-29 09:24 UTC, merged